name: Unity Package

on:
  workflow_call:
    inputs:
      package_base_path:
        type: string
        required: true
      package_title:
        type: string
        required: true
      package_workflow:
        type: string
        required: false
        default: "generate-docs.yml"
      package_artifact:
        type: string
        required: false
        default: "docs"
    secrets:
      token:
        required: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout package
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Checkout docs template
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          repository: zigurous/docs-template
          ref: unity-package
          path: docs~

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Setup docfx
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
          cache-dependency-path: docs~/yarn.lock

      - name: Increase network timeout
        run: yarn config set network-timeout 300000
        env:
          NPM_TOKEN: ${{ secrets.token }}

      - name: Install dependencies
        working-directory: docs~
        run: yarn install --prefer-offline
        env:
          NPM_TOKEN: ${{ secrets.token }}

      - name: Generate documentation
        working-directory: docs~
        run: yarn generate $env:PACKAGE_BASE_PATH $env:PACKAGE_TITLE
        env:
          NPM_TOKEN: ${{ secrets.token }}
          PACKAGE_BASE_PATH: ${{ inputs.package_base_path }}
          PACKAGE_TITLE: ${{ inputs.package_title }}

      - name: Build docs
        working-directory: docs~
        continue-on-error: false
        run: yarn build
        env:
          NPM_TOKEN: ${{ secrets.token }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs~/public
          retention-days: 30

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow
        uses: actions/github-script@v6
        env:
          PACKAGE_BASE_PATH: ${{ inputs.package_base_path }}
          PACKAGE_WORKFLOW: ${{ inputs.package_workflow }}
          PACKAGE_ARTIFACT: ${{ inputs.package_artifact }}
        with:
          github-token: ${{ secrets.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'zigurous',
              repo: 'docs',
              ref: 'main',
              workflow_id: 'publish-artifact.yml',
              inputs: {
                destination_path: process.env.PACKAGE_BASE_PATH,
                artifact_workflow: process.env.PACKAGE_WORKFLOW,
                artifact_name: process.env.PACKAGE_ARTIFACT,
                artifact_repo: process.env.GITHUB_REPOSITORY,
                artifact_commit: process.env.GITHUB_SHA
              }
            })
